### ISSUE TITLE
Reduce footprint of vite

### ISSUE THREAD

**Issue by 43081j** [es-tooling/ecosystem-cleanup#68]
vite currently has a few dependencies we could replace with lighter/faster alternatives.

Keep in mind, vite currently bundles its dependencies so they will not show up on npmgraph by default. If you'd like to see the "real" dependency tree, you can run the rollup bundle visualizer locally (in the vite repo).

## Tasks

- [ ] mjeanroy/rollup-plugin-license#1744
- [x] mjeanroy/rollup-plugin-license#1742
- [x] mjeanroy/rollup-plugin-license#1743
- [ ] #38
